# Generated by Django 3.1.1 on 2022-09-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlentificRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.CharField(blank=True, max_length=10, null=True)),
                ('col6', models.CharField(blank=True, max_length=10, null=True)),
                ('col7', models.CharField(blank=True, max_length=10, null=True)),
                ('col8', models.CharField(blank=True, max_length=10, null=True)),
                ('col9', models.CharField(blank=True, max_length=10, null=True)),
                ('col10', models.CharField(blank=True, max_length=10, null=True)),
                ('col11', models.CharField(blank=True, max_length=10, null=True)),
                ('col12', models.CharField(blank=True, max_length=10, null=True)),
                ('col13', models.CharField(blank=True, max_length=10, null=True)),
                ('col14', models.CharField(blank=True, max_length=10, null=True)),
                ('col15', models.CharField(blank=True, max_length=10, null=True)),
                ('col16', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
